parameters:
    config.defaults: {}
    config.template_base: 'base.html.twig'

services:
    Gupalo\ConfigBundle\Controller\ConfigController:
        class: Gupalo\ConfigBundle\Controller\ConfigController
        public: true
        autowire: true
        calls:
            - [setContainer, ["@service_container"]]
        tags: ['controller.service_arguments']

    Gupalo\ConfigBundle\Repository\ConfigRepository:
        class: Gupalo\ConfigBundle\Repository\ConfigRepository
        public: true
        autoconfigure: true
        autowire: true
        bind:
            $defaults: '%config.defaults%'
        tags: ['doctrine.repository_service']

